### ISSUE TITLE
[Bug 1.10.2] Crash when right click in non autorized area

### ISSUE THREAD

**Issue by AshleyXF** [ImagicTheCat/BlockProtectFieldGenerator#8]
Client crash after right clicking in a zone without permission. Because the event is not cancellable. (java.lang.IllegalArgumentException: Attempted to cancel a non cancellable event)

`java.lang.IllegalArgumentException: Attempted to cancel a non cancellable event
	at net.minecraftforge.fml.common.eventhandler.Event.setCanceled(Event.java:93)
	at imagicthecat.blockprotectfieldgenerator.shared.ForgeEventHandler.playerInteract(ForgeEventHandler.java:46)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_880_ForgeEventHandler_playerInteract_PlayerInteractEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.common.ForgeHooks.onEmptyClick(ForgeHooks.java:1032)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1543)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/BlockProtectFieldGenerator/commit/8efa4e0d75cb688685f5e92fb0c98aee610827ab
